spring:
    application:
        name: Asset-gateway

    cloud:
        gateway:
            routes:
                 - id: asset
                   uri: lb://asset
                   predicates:
                   - Path=/asset/**   


server:

        port: 8081

eureka:
    client:
        service-url:
                 defaultZone: http://localhost:8761/eureka                   
    instance:
        preferIpAddress: true 