spring:
    application:
        name: getway
    cloud:
      gateway:
        routes:
        - id: employee
          uri: lb://employee
          predicates:
              - Path=/employee/**
          filters:
              - StripPrefix=1

server:
    port: 8081


eureka:
    client:
        fetchRegistry: true
        registerWithEureka: true
        serviceUrl:
            defaultZeon: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
        preferIpAddress: true